// Pure Dart.
import '../entities/ci_options.dart';
import 'ci_options_validator.dart';
import 'postpilot_command.dart';

/// Writes `.github/workflows/postpilot.yml`: a workflow that checks out the repository and PostPilot, sets up Flutter,
/// runs the workspace with the command line, uploads the JUnit report, shows a summary on the job page and, on a failed
/// scheduled run, keeps one GitHub issue open about it.
///
/// Secrets are mapped by name only (`POSTPILOT_VAR_<variable>: ${{ secrets.<NAME> }}`): a value never reaches the file,
/// and they are given to the one step that runs the requests, not to the steps that fetch code.
abstract final class GithubWorkflowBuilder {
  /// Where the file goes in the repository.
  static const path = '.github/workflows/postpilot.yml';

  /// The label that finds the one open issue of a failing monitor.
  static const issueLabel = 'postpilot-monitor';

  /// The text of the workflow. Throws an [ArgumentError] that says what to change when [o] has a value that must not
  /// go into a command (see [CiOptionsValidator]); the dialog checks first and never gets that far.
  static String build(CiOptions o) {
    final problem = CiOptionsValidator.firstProblem(o);
    if (problem != null) throw ArgumentError(problem);
    final path = o.workspacePath.trim();
    final cron = o.cron;
    final issue = o.openIssueOnFailure && cron != null;
    final b = StringBuffer();

    b.writeln('# Generated by PostPilot ("Set up CI..."). Open that dialog again to change it; if you edit this file by hand,');
    b.writeln('# PostPilot asks before it replaces it.');
    b.writeln('#');
    b.writeln('# What it does: runs "$path" with the PostPilot command line on every push and pull request');
    b.writeln('# (and by hand from the Actions tab${cron == null ? '' : ', and on a schedule: the monitor'}), uploads report.xml,');
    b.writeln('# and writes a summary of what broke to the job page.');
    if (o.secrets.isNotEmpty) {
      b.writeln('#');
      b.writeln('# Create these repository secrets (Settings > Secrets and variables > Actions), one per secret variable:');
      for (final line in PostpilotCommand.secretLines(o)) {
        b.writeln('#   $line');
      }
      b.writeln('# Pull requests from forks do not receive secrets, so requests that need them fail there.');
    }
    if (o.allowProduction) {
      b.writeln('#');
      b.writeln('# WARNING: --allow-production is on. Every run, including each push and pull request, may send POST, PUT, PATCH');
      b.writeln('# and DELETE requests to production. Remove the flag to let the production lock refuse them.');
    }
    b.writeln('name: PostPilot API tests');
    b.writeln();
    b.writeln('on:');
    b.writeln('  push:');
    b.writeln('  pull_request:');
    b.writeln('  workflow_dispatch:');
    if (cron != null) {
      b.writeln('  schedule:');
      b.writeln('    # UTC. GitHub starts scheduled workflows at most every 5 minutes, and sometimes a few minutes late.');
      b.writeln('    - cron: ${ShellQuote.yaml(cron)}');
    }
    b.writeln();
    b.writeln('permissions:');
    b.writeln('  contents: read');
    b.writeln();
    b.writeln('jobs:');
    b.writeln('  api-tests:');
    b.writeln('    name: Run the PostPilot workspace');
    b.writeln('    runs-on: ubuntu-latest');
    b.writeln('    timeout-minutes: 30');
    if (issue) {
      b.writeln('    permissions:');
      b.writeln('      contents: read');
      b.writeln('      issues: write');
    }
    b.writeln('    steps:');
    b.writeln('      - name: Check out this repository');
    b.writeln('        uses: actions/checkout@v4');
    b.writeln();
    b.writeln('      - name: Check out PostPilot');
    b.writeln('        uses: actions/checkout@v4');
    b.writeln('        with:');
    b.writeln('          repository: ${PostpilotCommand.repositoryName}');
    b.writeln('          ref: ${ShellQuote.yaml(o.postpilotRef.trim())}');
    b.writeln('          path: .postpilot');
    b.writeln();
    b.writeln('      # PostPilot is a Flutter project: its pubspec needs the Flutter SDK for "pub get", even though the command');
    b.writeln('      # line itself is plain Dart.');
    b.writeln('      - name: Set up Flutter');
    b.writeln('        uses: subosito/flutter-action@v2');
    b.writeln('        with:');
    b.writeln('          channel: stable');
    b.writeln('          cache: true');
    b.writeln();
    b.writeln('      - name: Install PostPilot');
    b.writeln('        working-directory: .postpilot');
    b.writeln('        run: flutter pub get');
    b.writeln();
    b.writeln('      # The command line also appends a Markdown summary to \$GITHUB_STEP_SUMMARY by itself.');
    b.writeln('      - name: Run the requests');
    b.writeln('        working-directory: .postpilot');
    if (o.secrets.isNotEmpty) {
      b.writeln('        env:');
      for (final s in o.secrets) {
        b.writeln('          ${_key(s.processVariable)}: \${{ secrets.${s.secretName} }}');
      }
    }
    b.writeln('        run: |');
    b.writeln(PostpilotCommand.wrapped(
      o,
      workspace: '"\$GITHUB_WORKSPACE/$path"',
      report: '"\$GITHUB_WORKSPACE/${PostpilotCommand.reportFile}"',
      summary: issue ? '"\$GITHUB_WORKSPACE/${PostpilotCommand.summaryFile}"' : null,
      indent: '          ',
    ));
    b.writeln();
    b.writeln('      - name: Upload the report');
    b.writeln('        if: always()');
    b.writeln('        uses: actions/upload-artifact@v4');
    b.writeln('        with:');
    b.writeln('          name: postpilot-report');
    b.writeln('          path: ${PostpilotCommand.reportFile}');
    b.writeln('          if-no-files-found: ignore');
    if (issue) {
      b.writeln();
      b.writeln('      # One issue per failing monitor: found by its label, commented on while it stays open.');
      b.writeln('      - name: Open or update an issue');
      b.writeln("        if: failure() && github.event_name == 'schedule'");
      b.writeln('        env:');
      b.writeln('          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}');
      b.writeln('          RUN_URL: \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}');
      b.writeln('        run: |');
      for (final line in _issueScript) {
        b.writeln('          $line');
      }
    }
    return b.toString();
  }

  static const _issueScript = [
    "label='$issueLabel'",
    "title='PostPilot monitor: the scheduled API run failed'",
    '{',
    '  echo "The scheduled PostPilot run failed: \$RUN_URL"',
    '  echo',
    '  if [ -f ${PostpilotCommand.summaryFile} ]; then cat ${PostpilotCommand.summaryFile}; fi',
    '} > issue-body.md',
    'gh label create "\$label" --repo "\$GITHUB_REPOSITORY" --color B60205 --description \'A scheduled PostPilot run failed\' 2>/dev/null || true',
    'number=\$(gh issue list --repo "\$GITHUB_REPOSITORY" --label "\$label" --state open --limit 1 --json number --jq \'.[0].number // empty\')',
    'if [ -n "\$number" ]; then',
    '  gh issue comment "\$number" --repo "\$GITHUB_REPOSITORY" --body-file issue-body.md',
    'else',
    '  gh issue create --repo "\$GITHUB_REPOSITORY" --title "\$title" --label "\$label" --body-file issue-body.md',
    'fi',
  ];

  /// A YAML key: plain when it only holds letters, digits, `_`, `.` and `-`, else quoted.
  static String _key(String key) => RegExp(r'^[A-Za-z0-9_.-]+$').hasMatch(key) ? key : ShellQuote.yaml(key);
}
